source .env

docker run --name $POSTGRES_CONTAINER_NAME -d -e POSTGRES_PASSWORD=$PASSWORD_DOCKER_SQL -e POSTGRES_DB=$DATABASE_NAME-d -p $POSTGRES_HOST_PORT:$POSTGRES_PORT $POSTGRES_IMAGE_NAME 

docker logs $POSTGRES_CONTAINER_NAME